services:
  # Layanan untuk Database PostgreSQL (Tidak Perlu Diubah)
  db:
    image: postgres:14-alpine
    container_name: shop_db
    restart: always
    ports:
      - "5432:5432"
    env_file:
      - .env
    volumes:
      - ./.postgres-data:/var/lib/postgresql/data
      - ./db/init.sql:/docker-entrypoint-initdb.d/init.sql 
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U postgres -d shop_db"]
      interval: 10s
      timeout: 5s
      retries: 5
    networks:
      - microservices-net
  user-service:
    build:
      context: .
      dockerfile: user-service/Dockerfile
    container_name: user_service_app
    restart: always
    ports:
      - "${USER_SERVICE_PORT}:${USER_SERVICE_PORT}"
    env_file:
      - ./.env
    depends_on:
      db:
        condition: service_healthy
    networks:
      - microservices-net
  item-service:
    build:
      context: .
      dockerfile: item-service/Dockerfile
    container_name: item_service_app
    restart: always
    ports:
      - "${ITEM_SERVICE_PORT}:${ITEM_SERVICE_PORT}"
    env_file:
      - ./.env
    depends_on:
      db:
        condition: service_healthy
    networks:
      - microservices-net
  purchase-service:
    build:
      context: .
      dockerfile: purchase-service/Dockerfile
    container_name: purchase_service_app
    restart: always
    ports:
      - "${PURCHASE_SERVICE_PORT}:${PURCHASE_SERVICE_PORT}"
    env_file:
      - ./.env
    depends_on:
      db:
        condition: service_healthy
      item-service:
        condition: service_started
    networks:
      - microservices-net
networks:
  microservices-net:
    external: true