services:
  tempo:
    image: grafana/tempo:latest
    container_name: tempo
    restart: always
    ports:
      - "3200:3200"  # tempo query
      - "4317:4317"  # OTLP gRPC receiver
      - "4318:4318"  # OTLP HTTP receiver
    command: [ "-config.file=/etc/tempo.yaml" ]
    volumes:
      - ./tempo.yaml:/etc/tempo.yaml
      - ./tempo-data:/var/tempo
    networks:
      - microservices-net

networks:
  microservices-net:
    external: true
