# promtail-config.yaml

server:
  http_listen_port: 9080
  grpc_listen_port: 0

positions:
  filename: /tmp/positions.yaml

clients:
  - url: http://loki:3100/loki/api/v1/push

# Konfigurasi ini yang paling penting
scrape_configs:
  - job_name: containers
    # Menggunakan Docker service discovery untuk menemukan semua kontainer
    docker_sd_configs:
      - host: unix:///var/run/docker.sock
        refresh_interval: 5s
    # Memberi label 'container' pada setiap log stream
    relabel_configs:
      - source_labels: ['__meta_docker_container_name']
        regex: '/(.*)'
        target_label: 'container'