# services:
#   purchase-service:
#     build:
#       context: .
#       dockerfile: Dockerfile
#     container_name: purchase_service_app
#     ports:
#       - "${PURCHASE_SERVICE_PORT:-5002}:${PURCHASE_SERVICE_PORT:-5002}"
#     env_file:
#       - .env
#     # depends_on:
#       # shop_db:
#       #   condition: service_healthy
#     restart: always

#   # shop_db:
#   #   image: postgres:14-alpine
#   #   container_name: purchase_db
#   #   restart: always
#   #   ports:
#   #     - "5433:5432"
#   #   env_file:
#   #     - .env
#   #   volumes:
#   #     - ./.postgres-data:/var/lib/postgresql/data
#   #     - ./db/init.sql:/docker-entrypoint-initdb.d/init.sql
#   #   healthcheck:
#   #     test: ["CMD-SHELL", "pg_isready -U postgres -d ${DB_NAME}"]
#   #     interval: 10s
#   #     timeout: 5s
#   #     retries: 5